version: "3"

services:
  app:
    container_name: test-zpt-digital
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - .:/www/deno/app
    command: deno task dev